In [8]:
!wget https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt

--2026-09-13 10:17:50--  https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 2606:50c0:8001::154, 2606:50c0:8003::154, 2606:50c0:8002::154, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|2606:50c0:8001::154|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1115394 (1.1M) [text/plain]
Saving to: ‘input.txt’

input.txt           100%[===================>]   1.06M  5.34MB/s    in 0.2s    

2026-09-13 10:17:51 (5.34 MB/s) - ‘input.txt’ saved [1115394/1115394]



In [10]:
with open("input.txt") as f:
    text = f.read()

In [16]:
print(len(text))

1115394


In [23]:
chars = sorted(list(set(text)))
vocab_sz = len(chars)
print(''.join(chars))
print(vocab_sz)


 !$&',-.3:;?ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz
65


In [35]:
stoi = {ch:i for i, ch in enumerate(chars)}
itos = {i:ch for i, ch in enumerate(chars)}
encode = lambda s: [stoi[c] for c in s]
decode = lambda l: ''.join([itos[i] for i in l])

In [36]:
s = "hii there!"
print(encode(s))
print(decode(encode(s)))

[46, 47, 47, 1, 58, 46, 43, 56, 43, 2]
hii there!


In [43]:
import torch
data = torch.tensor(encode(text), dtype=torch.long)
print(data.shape, data.dtype)

torch.Size([1115394]) torch.int64


In [45]:
n = int(0.9*len(data))
train_data = data[:n]
val_data = data[n:]

In [46]:
print(data[:8])
print(data[8:16])

tensor([18, 47, 56, 57, 58,  1, 15, 47])
tensor([58, 47, 64, 43, 52, 10,  0, 14])


In [56]:
block_size = 8
x = train_data[:block_size]
y = train_data[1:block_size + 1]

print(x, y, sep='\n')

for t in range(block_size):
    context = x[:t+1]
    target = y[t]
    print(f"when input is {context}, the target is: {target}")

tensor([18, 47, 56, 57, 58,  1, 15, 47])
tensor([47, 56, 57, 58,  1, 15, 47, 58])
when input is tensor([18]), the target is: 47
when input is tensor([18, 47]), the target is: 56
when input is tensor([18, 47, 56]), the target is: 57
when input is tensor([18, 47, 56, 57]), the target is: 58
when input is tensor([18, 47, 56, 57, 58]), the target is: 1
when input is tensor([18, 47, 56, 57, 58,  1]), the target is: 15
when input is tensor([18, 47, 56, 57, 58,  1, 15]), the target is: 47
when input is tensor([18, 47, 56, 57, 58,  1, 15, 47]), the target is: 58
